export const LAYOUT_PROPS_CLASS_NAMES_MAP = {
  display: {
    inline: 'inline',
    block: 'block',
    'inline-block': 'inline-block',
    'flow-root': 'flow-root',
    flex: 'flex',
    'inline-flex': 'inline-flex',
    grid: 'grid',
    'inline-grid': 'inline-grid',
    contents: 'contents',
    table: 'table',
    'inline-table': 'inline-table',
    'table-caption': 'table-caption',
    'table-cell': 'table-cell',
    'table-column': 'table-column',
    'table-column-group': 'table-column-group',
    'table-footer-group': 'table-footer-group',
    'table-header-group': 'table-header-group',
    'table-row-group': 'table-row-group',
    'table-row': 'table-row',
    'list-item': 'list-item',
    none: 'hidden',
  },
  overflow: {
    auto: 'overflow-auto',
    hidden: 'overflow-hidden',
    clip: 'overflow-clip',
    visible: 'overflow-visible',
    scroll: 'overflow-scroll',
  },
  overflowX: {
    auto: 'overflow-y-auto',
    hidden: 'overflow-y-hidden',
    clip: 'overflow-y-clip',
    visible: 'overflow-y-visible',
    scroll: 'overflow-y-scroll',
  },
  overflowY: {
    auto: 'overflow-y-auto',
    hidden: 'overflow-y-hidden',
    clip: 'overflow-y-clip',
    visible: 'overflow-y-visible',
    scroll: 'overflow-y-scroll',
  },
  position: {
    static: 'static',
    fixed: 'fixed',
    absolute: 'absolute',
    relative: 'relative',
    sticky: 'sticky',
  },
  visibility: {
    visible: 'visible',
    hidden: 'invisible',
    collapse: 'collapse',
  },
  verticalAlign: {
    baseline: 'align-baseline',
    top: 'align-top',
    middle: 'align-middle',
    bottom: 'align-bottom',
    'text-top': 'align-text-top',
    'text-bottom': 'align-text-bottom',
    sub: 'align-sub',
    super: 'align-super',
  },
};

export const FLEX_PROPS_CLASS_NAMES_MAP = {
  flexDirection: {
    row: 'flex-row',
    'row-reverse': 'flex-row-reverse',
    column: 'flex-col',
    'column-reverse': 'flex-col-reverse',
  },
  flexWrap: {
    nowrap: 'flex-nowrap',
    wrap: 'flex-wrap',
    'wrap-reverse': 'flex-wrap-reverse',
  },
  justifyContent: {
    'flex-start': 'justify-start',
    'flex-end': 'justify-end',
    'safe flex-end': 'justify-end-safe',
    center: 'justify-center',
    'safe center': 'justify-center-safe',
    'space-between': 'justify-between',
    'space-around': 'justify-around',
    'space-evenly': 'justify-evenly',
    stretch: 'justify-stretch',
    normal: 'justify-normal',
  },
  justifySelf: {
    auto: 'justify-self-auto',
    start: 'justify-self-start',
    center: 'justify-self-center',
    'safe center': 'justify-self-center-safe',
    end: 'justify-self-end',
    'safe end': 'justify-self-end-safe',
    stretch: 'justify-self-stretch',
  },
  alignContent: {
    normal: 'content-normal',
    center: 'content-center',
    'flex-start': 'content-start',
    'flex-end': 'content-end',
    'space-between': 'content-between',
    'space-around': 'content-around',
    'space-evenly': 'content-evenly',
    baseline: 'content-baseline',
    stretch: 'content-stretch',
  },
  alignItems: {
    'flex-start': 'items-start',
    'flex-end': 'items-end',
    'safe flex-end': 'items-end-safe',
    center: 'items-center',
    'safe center': 'items-center-safe',
    baseline: 'items-baseline',
    'last baseline': 'items-baseline-last',
    stretch: 'items-stretch',
  },
  alignSelf: {
    auto: 'self-auto',
    'flex-start': 'self-start',
    'flex-end': 'self-end',
    'safe flex-end': 'self-end-safe',
    center: 'self-center',
    'safe center': 'self-center-safe',
    stretch: 'self-stretch',
    baseline: 'self-baseline',
    'last baseline': 'self-baseline-last',
  },
};

export const GRID_PROPS_CLASS_NAMES_MAP = {
  gridAutoFlow: {
    row: 'grid-flow-row',
    column: 'grid-flow-col',
    dense: 'grid-flow-dense',
    'row-dense': 'grid-flow-row-dense',
    'column-dense': 'grid-flow-col-dense',
  },
};
