export const defaultPresets = [
  { label: 'Relative to' },
  { value: 'last-30-seconds', label: 'Last 30 seconds' },
  { value: 'last-minute', label: 'Last minute' },
  { value: 'last-5-minutes', label: 'Last 5 minutes' },
  { value: 'last-10-minutes', label: 'Last 10 minutes' },
  { value: 'last-15-minutes', label: 'Last 15 minutes' },
  { value: 'last-30-minutes', label: 'Last 30 minutes' },
  { value: 'last-45-minutes', label: 'Last 45 minutes' },
  { value: 'last-hour', label: 'Last hour' },
  { value: 'last-3-hours', label: 'Last 3 hours' },
  { value: 'last-6-hours', label: 'Last 6 hours' },
  { value: 'last-12-hours', label: 'Last 12 hours' },
  { value: 'last-day', label: 'Last 1 day' },
  { value: 'last-2-days', label: 'Last 2 days' },
  { value: 'last-7-days', label: 'Last 7 days' },
  { value: 'last-15-days', label: 'Last 15 days' },
  { value: 'last-month', label: 'Last month' },
  { value: 'last-2-month', label: 'Last 2 months' },
  { value: 'last-3-month', label: 'Last 3 months' },
  { value: 'last-6-month', label: 'Last 6 months' },
  { value: 'last-year', label: 'Last year' },
  { label: 'Snap to' },
  { value: 'minute', label: 'Minute' },
  { value: 'hour', label: 'Hour' },
  { value: 'day', label: 'Day' },
  { value: 'iso-week', label: 'ISO week' },
  { value: 'week', label: 'Week' },
  { value: 'month', label: 'Month' },
  { value: 'year', label: 'Year' },
];

export const presetsMapToRanges = {
  'last-30-seconds': ['now() - 30s', 'now()'],
  'last-minute': ['now() - 1m', 'now()'],
  'last-5-minutes': ['now() - 5m', 'now()'],
  'last-10-minutes': ['now() - 10m', 'now()'],
  'last-15-minutes': ['now() - 15m', 'now()'],
  'last-30-minutes': ['now() - 30m', 'now()'],
  'last-45-minutes': ['now() - 45m', 'now()'],
  'last-hour': ['now() - 1h', 'now()'],
  'last-3-hours': ['now() - 3h', 'now()'],
  'last-6-hours': ['now() - 6h', 'now()'],
  'last-12-hours': ['now() - 12h', 'now()'],
  'last-day': ['now() - 1d', 'now()'],
  'last-2-days': ['now() - 2d', 'now()'],
  'last-7-days': ['now() - 7d', 'now()'],
  'last-15-days': ['now() - 15d', 'now()'],
  'last-month': ['now() - 30d', 'now()'],
  'last-2-month': ['now() - 60d', 'now()'],
  'last-3-month': ['now() - 90d', 'now()'],
  'last-6-month': ['now() - 180d', 'now()'],
  'last-year': ['now() - 365d', 'now()'],
  minute: ['now() @ 1m', 'now()'],
  hour: ['now() @ 1h', 'now()'],
  day: ['now() @ 1d', 'now()'],
  'iso-week': ['now() @ 1W', 'now()'],
  week: ['now() @ 1w', 'now()'],
  month: ['now() @ 1M', 'now()'],
  year: ['now() @ 1y', 'now()'],
};
