import {
  startOfDay,
  startOfHour,
  startOfMinute,
  startOfMonth,
  startOfWeek,
  startOfYear,
  subDays,
  subHours,
  subMinutes,
  subMonths,
  subSeconds,
  subYears,
} from 'date-fns';

//export const defaultPresets = [
//  { label: 'Relative to' },
//  { value: ['now() - 30s', 'now()'], label: 'Last 30 seconds' },
//  { value: ['now() - 1m', 'now()'], label: 'Last minute' },
//  { value: ['now() - 5m', 'now()'], label: 'Last 5 minutes' },
//  { value: ['now() - 10m', 'now()'], label: 'Last 10 minutes' },
//  { value: ['now() - 15m', 'now()'], label: 'Last 15 minutes' },
//  { value: ['now() - 30m', 'now()'], label: 'Last 30 minutes' },
//  { value: ['now() - 45m', 'now()'], label: 'Last 45 minutes' },
//  { value: ['now() - 1h', 'now()'], label: 'Last hour' },
//  { value: ['now() - 3h', 'now()'], label: 'Last 3 hours' },
//  { value: ['now() - 6h', 'now()'], label: 'Last 6 hours' },
//  { value: ['now() - 12h', 'now()'], label: 'Last 12 hours' },
//  { value: ['now() - 1d', 'now()'], label: 'Last 1 day' },
//  { value: ['now() - 2d', 'now()'], label: 'Last 2 days' },
//  { value: ['now() - 7d', 'now()'], label: 'Last 7 days' },
//  { value: ['now() - 15d', 'now()'], label: 'Last 15 days' },
//  { value: ['now() - 30d', 'now()'], label: 'Last month' },
//  { value: ['now() - 60d', 'now()'], label: 'Last 2 months' },
//  { value: ['now() - 90d', 'now()'], label: 'Last 3 months' },
//  { value: ['now() - 180d', 'now()'], label: 'Last 6 months' },
//  { value: ['now() - 365d', 'now()'], label: 'Last year' },
//  { label: 'Snap to' },
//  { value: ['now() @ 1m', 'now()'], label: 'Minute' },
//  { value: ['now() @ 1h', 'now()'], label: 'Hour' },
//  { value: ['now() @ 1d', 'now()'], label: 'Day' },
//  { value: ['now() @ 1W', 'now()'], label: 'ISO week' },
//  { value: ['now() @ 1w', 'now()'], label: 'Week' },
//  { value: ['now() @ 1M', 'now()'], label: 'Month' },
//  { value: ['now() @ 1y', 'now()'], label: 'Year' },
//];

export const getDefaultRelativeRanges = (now = new Date().getTime()) => [
  { value: [subSeconds(now, 30).getTime(), now], label: 'Last 30 seconds' },
  { value: [subMinutes(now, 1).getTime(), now], label: 'Last minute' },
  { value: [subMinutes(now, 5).getTime(), now], label: 'Last 5 minutes' },
  { value: [subMinutes(now, 10).getTime(), now], label: 'Last 10 minutes' },
  { value: [subMinutes(now, 15).getTime(), now], label: 'Last 15 minutes' },
  { value: [subMinutes(now, 30).getTime(), now], label: 'Last 30 minutes' },
  { value: [subMinutes(now, 45).getTime(), now], label: 'Last 45 minutes' },
  { value: [subHours(now, 1).getTime(), now], label: 'Last hour' },
  { value: [subHours(now, 3).getTime(), now], label: 'Last 3 hours' },
  { value: [subHours(now, 6).getTime(), now], label: 'Last 6 hours' },
  { value: [subHours(now, 12).getTime(), now], label: 'Last 12 hours' },
  { value: [subDays(now, 1).getTime(), now], label: 'Last 1 day' },
  { value: [subDays(now, 2).getTime(), now], label: 'Last 2 days' },
  { value: [subDays(now, 7).getTime(), now], label: 'Last 7 days' },
  { value: [subDays(now, 15).getTime(), now], label: 'Last 15 days' },
  { value: [subMonths(now, 1).getTime(), now], label: 'Last month' },
  { value: [subMonths(now, 2).getTime(), now], label: 'Last 2 months' },
  { value: [subMonths(now, 3).getTime(), now], label: 'Last 3 months' },
  { value: [subMonths(now, 6).getTime(), now], label: 'Last 6 months' },
  { value: [subYears(now, 1).getTime(), now], label: 'Last year' },
];

export const getDefaultSnapRanges = (now = new Date().getTime()) => [
  { value: [startOfMinute(now).getTime(), now], label: 'Minute' },
  { value: [startOfHour(now).getTime(), now], label: 'Hour' },
  { value: [startOfDay(now).getTime(), now], label: 'Day' },
  { value: [startOfWeek(now), now], label: 'Week' },
  { value: [startOfMonth(now), now], label: 'Month' },
  { value: [startOfYear(now), now], label: 'Year' },
];

export const getDefaultPresets = (now = new Date().getTime()) => [
  { label: 'Relative to' },
  ...getDefaultRelativeRanges(now),
  { label: 'Snap to' },
  ...getDefaultSnapRanges(now),
];
