name: release

on:
  workflow_dispatch:
    inputs:
      dry:
        type: boolean
        description: Dry-mode (simulate publish)?
        default: true
        required: true
      version:
        type: choice
        description: Select version to release
        options:
          - major
          - minor
          - patch
          - prerelease
          - auto
        default: auto
        required: true

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            ~/.npm
            **/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Set Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Generate dist
        run: npm run build

  lint:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            ~/.npm
            **/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Run linter
        run: npm run lint

  unit-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            ~/.npm
            **/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Run tests
        run: npm t

  release:
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            node_modules
            ~/.npm
            **/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Setup Git config
        run: |
          git config --global user.name 'Devo GitHub Action'
          git config --global user.email 'desa@devo.com'

      - name: Publish ${{ github.event.inputs.version }} (dry-run)
        if: ${{ github.event.inputs.version != 'auto' && github.event.inputs.dry == 'true' }}
        run: npm run release:ci -- ${{ github.event.inputs.version }} --dry-run

      - name: Publish prerelease (dry-run)
        if: ${{ github.event.inputs.version == 'prerelease' && github.event.inputs.dry == 'true' }}
        run: npm run release:ci -- --preRelease --dry-run

      - name: Publish 'auto' (dry-run)
        if: ${{ github.event.inputs.version == 'auto' && github.event.inputs.dry == 'true' }}
        run: npm run release:ci --dry-run

      - name: Publish ${{ github.event.inputs.version }}
        if: ${{ github.event.inputs.version != 'auto' && github.event.inputs.dry == 'false' }}
        run: npm run release:ci -- ${{ github.event.inputs.version }}

      - name: Publish prerelease
        if: ${{ github.event.inputs.version == 'prerelease' && github.event.inputs.dry == 'false' }}
        run: npm run release:ci -- --preRelease

      - name: Publish 'auto'
        if: ${{ github.event.inputs.version == 'auto' && github.event.inputs.dry == 'false' }}
        run: npm run release:ci
